// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6KGs6BxbpYF9vG7fVGy6hgdxO5Prk0P0',
    appId: '1:1049713340574:web:d3caf0616add86fcbc4b8f',
    messagingSenderId: '1049713340574',
    projectId: 'furn-app-819aa',
    authDomain: 'furn-app-819aa.firebaseapp.com',
    databaseURL: 'https://furn-app-819aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furn-app-819aa.firebasestorage.app',
    measurementId: 'G-GERFKRF0TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdm43T1rInuKooY89H9FIY1E4mriLE1Fw',
    appId: '1:1049713340574:android:54751ac7d21bd51dbc4b8f',
    messagingSenderId: '1049713340574',
    projectId: 'furn-app-819aa',
    databaseURL: 'https://furn-app-819aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furn-app-819aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Fy3LA6Tj-eK00rpOfiBtCY8A7ItaMu4',
    appId: '1:1049713340574:ios:ae73377066cb9f0fbc4b8f',
    messagingSenderId: '1049713340574',
    projectId: 'furn-app-819aa',
    databaseURL: 'https://furn-app-819aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furn-app-819aa.firebasestorage.app',
    iosBundleId: 'com.example.furnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6KGs6BxbpYF9vG7fVGy6hgdxO5Prk0P0',
    appId: '1:1049713340574:web:2cba092b0e3ce7e6bc4b8f',
    messagingSenderId: '1049713340574',
    projectId: 'furn-app-819aa',
    authDomain: 'furn-app-819aa.firebaseapp.com',
    databaseURL: 'https://furn-app-819aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furn-app-819aa.firebasestorage.app',
    measurementId: 'G-LSJ2RGL7P8',
  );

}

